In [ ]:
import torch
from torch import Tensor

In [ ]:
from torch.distributions.normal import Normal
from torch.distributions.utils import broadcast_all

In [ ]:
Normal(0.0, 1.0).cdf(0.1)

ValueError: The value argument to log_prob must be a Tensor

In [ ]:
a = torch.tensor([-1.0, 0.0, 10.0])

In [ ]:
a

tensor([-1.,  0., 10.])

In [ ]:
Normal(0.0, 1.0).cdf(a)

tensor([0.1587, 0.5000, 1.0000])

In [ ]:
Normal(0.0, 1.0).log_prob(a)

tensor([ -1.4189,  -0.9189, -50.9189])

In [ ]:
Normal(0.0, 1.0).log_prob(a).exp()

tensor([2.4197e-01, 3.9894e-01, 7.6946e-23])

### $$d_1$$

$$d_1 = \frac{\ln \left( \frac{S_t}{K}\right) + (r + \frac{1}{2} \sigma^2) \sqrt{T-t}}{\sigma \sqrt{T-t}}$$

```
s, t, v = broadcast_all(log_moneyness, time_to_maturity, volatility)
if not (t >= 0).all():
    raise ValueError("all elements in time_to_maturity have to be non-negative")
if not (v >= 0).all():
    raise ValueError("all elements in volatility have to be non-negative")
variance = v * t.sqrt()
output = s / variance + variance / 2
# TODO(simaki): Replace zeros_like with 0.0 once https://github.com/pytorch/pytorch/pull/62084 is merged
return output.where((s != 0).logical_or(variance != 0), torch.zeros_like(output))
```