In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import torch

In [ ]:
!pip install pfhedge

In [ ]:
import pfhedge

In [ ]:
pfhedge.stochastic.generate_geometric_brownian(2,10)

tensor([[1.0000, 1.0069, 1.0241, 1.0016, 1.0074, 1.0074, 0.9955, 0.9837, 0.9731,
         0.9676],
        [1.0000, 1.0038, 1.0094, 0.9917, 0.9870, 0.9917, 0.9937, 1.0076, 1.0354,
         1.0260]])

In [ ]:
temp

tensor([[1.0000, 1.0143, 1.0102, 1.0035, 1.0115, 1.0062, 1.0098, 1.0162, 1.0101,
         1.0095],
        [1.0000, 1.0010, 0.9860, 0.9801, 0.9791, 0.9769, 0.9964, 0.9993, 1.0298,
         1.0374]])

In [ ]:
from pfhedge.instruments import BrownianStock
from pfhedge.instruments import EuropeanOption
from pfhedge.nn import BlackScholes

In [ ]:
stock = BrownianStock()
derivative = EuropeanOption(stock, strike=1.1)
derivative

EuropeanOption(
  strike=1.1000, maturity=0.0800
  (underlier): BrownianStock(sigma=0.2000, dt=0.0040)
)

In [ ]:
m = BlackScholes(derivative)
m

BSEuropeanOption(strike=1.1000)

In [ ]:
m.inputs()

['log_moneyness', 'time_to_maturity', 'volatility']

In [ ]:
stock.simulate(2)

In [ ]:
stock.spot

tensor([[1.0000, 0.9810, 0.9771, 0.9735, 0.9673, 0.9484, 0.9381, 0.9573, 0.9471,
         0.9386, 0.9358, 0.9331, 0.9217, 0.9196, 0.9209, 0.9366, 0.9348, 0.9151,
         0.9114, 0.9151, 0.9134],
        [1.0000, 0.9761, 1.0067, 0.9951, 0.9922, 1.0029, 1.0217, 1.0045, 0.9916,
         0.9970, 0.9952, 0.9963, 1.0123, 1.0080, 0.9959, 1.0009, 1.0109, 1.0275,
         1.0422, 1.0553, 1.0605]])

In [ ]:
derivative.moneyness()

tensor([[0.9091, 0.8919, 0.8883, 0.8850, 0.8794, 0.8622, 0.8528, 0.8703, 0.8610,
         0.8533, 0.8508, 0.8482, 0.8379, 0.8360, 0.8371, 0.8514, 0.8498, 0.8319,
         0.8286, 0.8319, 0.8303],
        [0.9091, 0.8874, 0.9152, 0.9046, 0.9020, 0.9117, 0.9288, 0.9132, 0.9015,
         0.9063, 0.9047, 0.9058, 0.9203, 0.9164, 0.9054, 0.9099, 0.9190, 0.9341,
         0.9475, 0.9594, 0.9641]])

In [ ]:
stock.spot / 1.1

tensor([[0.9091, 0.8919, 0.8883, 0.8850, 0.8794, 0.8622, 0.8528, 0.8703, 0.8610,
         0.8533, 0.8508, 0.8482, 0.8379, 0.8360, 0.8371, 0.8514, 0.8498, 0.8319,
         0.8286, 0.8319, 0.8303],
        [0.9091, 0.8874, 0.9152, 0.9046, 0.9020, 0.9117, 0.9288, 0.9132, 0.9015,
         0.9063, 0.9047, 0.9058, 0.9203, 0.9164, 0.9054, 0.9099, 0.9190, 0.9341,
         0.9475, 0.9594, 0.9641]])

In [ ]:
derivative.time_to_maturity()

tensor([[0.0800, 0.0760, 0.0720, 0.0680, 0.0640, 0.0600, 0.0560, 0.0520, 0.0480,
         0.0440, 0.0400, 0.0360, 0.0320, 0.0280, 0.0240, 0.0200, 0.0160, 0.0120,
         0.0080, 0.0040, 0.0000],
        [0.0800, 0.0760, 0.0720, 0.0680, 0.0640, 0.0600, 0.0560, 0.0520, 0.0480,
         0.0440, 0.0400, 0.0360, 0.0320, 0.0280, 0.0240, 0.0200, 0.0160, 0.0120,
         0.0080, 0.0040, 0.0000]])

In [ ]:
stock.volatility

tensor([[0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000,
         0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000,
         0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000,
         0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000,
         0.2000, 0.2000, 0.2000]])

In [ ]:
log_moneyness = derivative.log_moneyness()

In [ ]:
time_to_maturity = derivative.time_to_maturity()

In [ ]:
volatility = stock.volatility

In [ ]:
torch.cat([log_moneyness, time_to_maturity, volatility])

tensor([[-0.0953, -0.1145, -0.1185, -0.1222, -0.1286, -0.1483, -0.1592, -0.1390,
         -0.1496, -0.1587, -0.1616, -0.1646, -0.1769, -0.1792, -0.1778, -0.1608,
         -0.1628, -0.1840, -0.1880, -0.1840, -0.1859],
        [-0.0953, -0.1195, -0.0887, -0.1002, -0.1032, -0.0925, -0.0738, -0.0908,
         -0.1037, -0.0983, -0.1001, -0.0990, -0.0831, -0.0873, -0.0994, -0.0944,
         -0.0844, -0.0682, -0.0539, -0.0415, -0.0366],
        [ 0.0800,  0.0760,  0.0720,  0.0680,  0.0640,  0.0600,  0.0560,  0.0520,
          0.0480,  0.0440,  0.0400,  0.0360,  0.0320,  0.0280,  0.0240,  0.0200,
          0.0160,  0.0120,  0.0080,  0.0040,  0.0000],
        [ 0.0800,  0.0760,  0.0720,  0.0680,  0.0640,  0.0600,  0.0560,  0.0520,
          0.0480,  0.0440,  0.0400,  0.0360,  0.0320,  0.0280,  0.0240,  0.0200,
          0.0160,  0.0120,  0.0080,  0.0040,  0.0000],
        [ 0.2000,  0.2000,  0.2000,  0.2000,  0.2000,  0.2000,  0.2000,  0.2000,
          0.2000,  0.2000,  0.2000,  0.2000,  0.200

In [ ]:
log_moneyness.shape

torch.Size([2, 21])

In [ ]:
time_to_maturity.shape

torch.Size([2, 21])

In [ ]:
volatility.shape

torch.Size([2, 21])

In [ ]:
torch.cat([log_moneyness, time_to_maturity, volatility]).shape

torch.Size([6, 21])

In [ ]:
torch.cat([log_moneyness.unsqueeze(-1) for i in range(3)], dim=2)

torch.Size([2, 21, 3])

In [ ]:
f = [log_moneyness, time_to_maturity, volatility]

result = torch.cat([t.unsqueeze(-1) for t in f], dim=2)
result

tensor([[[-0.0953,  0.0800,  0.2000],
         [-0.1145,  0.0760,  0.2000],
         [-0.1185,  0.0720,  0.2000],
         [-0.1222,  0.0680,  0.2000],
         [-0.1286,  0.0640,  0.2000],
         [-0.1483,  0.0600,  0.2000],
         [-0.1592,  0.0560,  0.2000],
         [-0.1390,  0.0520,  0.2000],
         [-0.1496,  0.0480,  0.2000],
         [-0.1587,  0.0440,  0.2000],
         [-0.1616,  0.0400,  0.2000],
         [-0.1646,  0.0360,  0.2000],
         [-0.1769,  0.0320,  0.2000],
         [-0.1792,  0.0280,  0.2000],
         [-0.1778,  0.0240,  0.2000],
         [-0.1608,  0.0200,  0.2000],
         [-0.1628,  0.0160,  0.2000],
         [-0.1840,  0.0120,  0.2000],
         [-0.1880,  0.0080,  0.2000],
         [-0.1840,  0.0040,  0.2000],
         [-0.1859,  0.0000,  0.2000]],

        [[-0.0953,  0.0800,  0.2000],
         [-0.1195,  0.0760,  0.2000],
         [-0.0887,  0.0720,  0.2000],
         [-0.1002,  0.0680,  0.2000],
         [-0.1032,  0.0640,  0.2000],
         [

In [ ]:
input = result

In [ ]:
m(input)

tensor([[[4.8802e-02],
         [2.0265e-02],
         [1.4584e-02],
         [1.0255e-02],
         [5.9394e-03],
         [1.3377e-03],
         [4.1863e-04],
         [1.2467e-03],
         [3.4520e-04],
         [8.4639e-05],
         [2.9027e-05],
         [7.8380e-06],
         [4.1723e-07],
         [5.9605e-08],
         [0.0000e+00],
         [0.0000e+00],
         [0.0000e+00],
         [0.0000e+00],
         [0.0000e+00],
         [0.0000e+00],
         [0.0000e+00]],

        [[4.8802e-02],
         [1.6181e-02],
         [5.2052e-02],
         [2.9002e-02],
         [2.2028e-02],
         [3.1240e-02],
         [6.2271e-02],
         [2.4468e-02],
         [9.5034e-03],
         [1.0086e-02],
         [6.5035e-03],
         [4.8117e-03],
         [1.0602e-02],
         [4.7534e-03],
         [7.0578e-04],
         [4.4379e-04],
         [4.4236e-04],
         [9.5826e-04],
         [1.3234e-03],
         [5.3591e-04],
         [0.0000e+00]]])

In [ ]:
delta = torch.tensor([m(input[:,i]) for i in range(input.shape[1])]).unsqueeze(0)

In [ ]:
input.shape[1]

21

In [ ]:
pfhedge.nn.functional.pl(stock.spot, m(input).squeeze(-1))

tensor(-0.0031)

In [ ]:
stock.spot.unsqueeze(1).shape

torch.Size([2, 1, 21])

In [ ]:
m(input).squeeze(-1).unsqueeze(1).shape

torch.Size([2, 1, 21])

In [ ]:
pfhedge.nn.functional.pl(stock.spot.unsqueeze(1), m(input).squeeze(-1).unsqueeze(1))

tensor([-0.0013, -0.0019])