In [ ]:
!pip install pfhedge

### Last time

```
pfhedge.nn.functional.pl(stock.spot.unsqueeze(1), m(input).squeeze(-1).unsqueeze(1))
```

### Setup

In [ ]:
import pfhedge

In [ ]:
from pfhedge.instruments import BrownianStock
from pfhedge.instruments import EuropeanOption
from pfhedge.nn import BlackScholes

In [ ]:
stock = BrownianStock()
derivative = EuropeanOption(stock, strike=1.0)
derivative

EuropeanOption(
  strike=1., maturity=0.0800
  (underlier): BrownianStock(sigma=0.2000, dt=0.0040)
)

In [ ]:
m = BlackScholes(derivative)
m

BSEuropeanOption(strike=1.)

### Features

In [ ]:
stock.simulate()

In [ ]:
stock.spot

tensor([[1.0000, 0.9843, 0.9885, 0.9842, 0.9743, 0.9612, 0.9608, 0.9551, 0.9315,
         0.9075, 0.9124, 0.9208, 0.9260, 0.9159, 0.9147, 0.9154, 0.8983, 0.8940,
         0.9014, 0.8970, 0.8993]])

In [ ]:
derivative.simulate()

In [ ]:
stock.spot

tensor([[1.0000, 1.0023, 0.9926, 0.9792, 0.9725, 0.9647, 0.9898, 0.9775, 0.9751,
         0.9932, 0.9816, 0.9732, 0.9769, 0.9632, 0.9478, 0.9519, 0.9253, 0.9146,
         0.9136, 0.9238, 0.9354]])

In [ ]:
derivative.ul()

BrownianStock(sigma=0.2000, dt=0.0040)

In [ ]:
derivative.ul().spot

tensor([[1.0000, 1.0023, 0.9926, 0.9792, 0.9725, 0.9647, 0.9898, 0.9775, 0.9751,
         0.9932, 0.9816, 0.9732, 0.9769, 0.9632, 0.9478, 0.9519, 0.9253, 0.9146,
         0.9136, 0.9238, 0.9354]])

In [ ]:
derivative.log_moneyness()

tensor([[ 0.0000,  0.0023, -0.0075, -0.0210, -0.0279, -0.0359, -0.0103, -0.0227,
         -0.0252, -0.0068, -0.0185, -0.0271, -0.0234, -0.0375, -0.0536, -0.0493,
         -0.0776, -0.0892, -0.0903, -0.0792, -0.0667]])

In [ ]:
derivative.time_to_maturity()

tensor([[0.0800, 0.0760, 0.0720, 0.0680, 0.0640, 0.0600, 0.0560, 0.0520, 0.0480,
         0.0440, 0.0400, 0.0360, 0.0320, 0.0280, 0.0240, 0.0200, 0.0160, 0.0120,
         0.0080, 0.0040, 0.0000]])

In [ ]:
derivative.ul().volatility

tensor([[0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000,
         0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.2000,
         0.2000, 0.2000, 0.2000]])

### Dataset Manipulation

In [ ]:
derivative.simulate(2)

In [ ]:
lm = derivative.log_moneyness()
t = derivative.time_to_maturity()
v = derivative.ul().volatility

### torch.stack vs. torch.cat
[ChaptGPT] torch.stack vs. torch.cat

In [ ]:
import torch

In [ ]:
lm.size(), t.size(), v.size()

(torch.Size([2, 21]), torch.Size([2, 21]), torch.Size([2, 21]))

In [ ]:
torch.stack([lm, t, v]).size()

torch.Size([3, 2, 21])

In [ ]:
torch.cat([lm, t, v]).size()

torch.Size([6, 21])

In [ ]:
torch.stack([lm, t, v], dim=-1).size()

torch.Size([2, 21, 3])

In [ ]:
torch.cat([lm, t, v], dim=-1).size()

torch.Size([2, 63])

In [ ]:
torch.cat([lm.unsqueeze(-1), t.unsqueeze(-1), v.unsqueeze(-1)], dim=2).size()

torch.Size([2, 21, 3])

In [ ]:
lm.unsqueeze(-1).size()

torch.Size([2, 21, 1])

### Back to the topic

In [ ]:
torch.stack([lm, t, v], dim=-1).size()

torch.Size([2, 21, 3])

In [ ]:
torch.stack([lm, t, v], dim=-1)

tensor([[[ 0.0000,  0.0800,  0.2000],
         [ 0.0045,  0.0760,  0.2000],
         [ 0.0021,  0.0720,  0.2000],
         [ 0.0061,  0.0680,  0.2000],
         [ 0.0052,  0.0640,  0.2000],
         [ 0.0100,  0.0600,  0.2000],
         [-0.0097,  0.0560,  0.2000],
         [-0.0077,  0.0520,  0.2000],
         [-0.0005,  0.0480,  0.2000],
         [ 0.0081,  0.0440,  0.2000],
         [ 0.0102,  0.0400,  0.2000],
         [-0.0018,  0.0360,  0.2000],
         [-0.0036,  0.0320,  0.2000],
         [ 0.0190,  0.0280,  0.2000],
         [ 0.0239,  0.0240,  0.2000],
         [ 0.0131,  0.0200,  0.2000],
         [-0.0095,  0.0160,  0.2000],
         [-0.0249,  0.0120,  0.2000],
         [-0.0252,  0.0080,  0.2000],
         [-0.0276,  0.0040,  0.2000],
         [-0.0627,  0.0000,  0.2000]],

        [[ 0.0000,  0.0800,  0.2000],
         [-0.0091,  0.0760,  0.2000],
         [-0.0204,  0.0720,  0.2000],
         [-0.0090,  0.0680,  0.2000],
         [-0.0174,  0.0640,  0.2000],
         [

### torch.utils.data

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

In [ ]:
class MyDataset(Dataset):

    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index]

In [ ]:
ds = MyDataset(lm)

In [ ]:
len(ds)

2

In [ ]:
ds

In [ ]:
ids = iter(ds)

In [ ]:
next(ids)

StopIteration: 

### updated version

In [ ]:
class MyDataset(Dataset):

    def __init__(self, data):
        self.data = data

    def __len__(self):
        return self.data.size(1)

    def __getitem__(self, index):
        return self.data[:,index]

In [ ]:
ds = MyDataset(lm)

In [ ]:
for i in ds:
    print(i)
    print("----")

In [ ]:
ds = MyDataset(torch.stack([lm, t, v], dim=-1))

In [ ]:
len(ds)

In [ ]:
for i in ds:
    print(i)

### updated version 2

In [ ]:
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = torch.stack(data, dim=-1)

    def __len__(self):
        return self.data.size(1)

    def __getitem__(self, index):
        #return self.data[:, index, :]
        return self.data[:, index, :].unsqueeze(1)


In [ ]:
ds = MyDataset([lm, t, v])

In [ ]:
for i in ds:
    print(i)

tensor([[[0.0000, 0.0800, 0.2000]],

        [[0.0000, 0.0800, 0.2000]]])
tensor([[[ 0.0045,  0.0760,  0.2000]],

        [[-0.0091,  0.0760,  0.2000]]])
tensor([[[ 0.0021,  0.0720,  0.2000]],

        [[-0.0204,  0.0720,  0.2000]]])
tensor([[[ 0.0061,  0.0680,  0.2000]],

        [[-0.0090,  0.0680,  0.2000]]])
tensor([[[ 0.0052,  0.0640,  0.2000]],

        [[-0.0174,  0.0640,  0.2000]]])
tensor([[[ 0.0100,  0.0600,  0.2000]],

        [[-0.0420,  0.0600,  0.2000]]])
tensor([[[-0.0097,  0.0560,  0.2000]],

        [[-0.0405,  0.0560,  0.2000]]])
tensor([[[-0.0077,  0.0520,  0.2000]],

        [[-0.0253,  0.0520,  0.2000]]])
tensor([[[-0.0005,  0.0480,  0.2000]],

        [[-0.0193,  0.0480,  0.2000]]])
tensor([[[ 0.0081,  0.0440,  0.2000]],

        [[-0.0238,  0.0440,  0.2000]]])
tensor([[[ 0.0102,  0.0400,  0.2000]],

        [[-0.0261,  0.0400,  0.2000]]])
tensor([[[-0.0018,  0.0360,  0.2000]],

        [[ 0.0040,  0.0360,  0.2000]]])
tensor([[[-0.0036,  0.0320,  0.2000]],

      

### Black-Scholes

In [ ]:
from pfhedge.nn import BlackScholes

In [ ]:
m = BlackScholes(derivative)

[european.py](https://github.com/pfnet-research/pfhedge/blob/main/pfhedge/nn/modules/bs/european.py#L106)

In [ ]:
m

BSEuropeanOption(strike=1.)

In [ ]:
m.delta()

tensor([[0.5113, 0.5437, 0.5260, 0.5570, 0.5506, 0.5906, 0.4279, 0.4419, 0.5038,
         0.5847, 0.6083, 0.4884, 0.4666, 0.7203, 0.7841, 0.6837, 0.3580, 0.1302,
         0.0810, 0.0149, 0.0000],
        [0.5113, 0.4451, 0.3618, 0.4419, 0.3753, 0.2024, 0.2027, 0.2976, 0.3381,
         0.2925, 0.2637, 0.5492, 0.6425, 0.7507, 0.7665, 0.7464, 0.8613, 0.7593,
         0.7390, 0.0127, 0.0000]])

In [ ]:
m.delta(lm, t, v)

tensor([[0.5113, 0.5437, 0.5260, 0.5570, 0.5506, 0.5906, 0.4279, 0.4419, 0.5038,
         0.5847, 0.6083, 0.4884, 0.4666, 0.7203, 0.7841, 0.6837, 0.3580, 0.1302,
         0.0810, 0.0149, 0.0000],
        [0.5113, 0.4451, 0.3618, 0.4419, 0.3753, 0.2024, 0.2027, 0.2976, 0.3381,
         0.2925, 0.2637, 0.5492, 0.6425, 0.7507, 0.7665, 0.7464, 0.8613, 0.7593,
         0.7390, 0.0127, 0.0000]])

In [ ]:
for i in ds:
    print(m(i))

tensor([[0.5113],
        [0.5113]])
tensor([[0.5437],
        [0.4451]])
tensor([[0.5260],
        [0.3618]])
tensor([[0.5570],
        [0.4419]])
tensor([[0.5506],
        [0.3753]])
tensor([[0.5906],
        [0.2024]])
tensor([[0.4279],
        [0.2027]])
tensor([[0.4419],
        [0.2976]])
tensor([[0.5038],
        [0.3381]])
tensor([[0.5847],
        [0.2925]])
tensor([[0.6083],
        [0.2637]])
tensor([[0.4884],
        [0.5492]])
tensor([[0.4666],
        [0.6425]])
tensor([[0.7203],
        [0.7507]])
tensor([[0.7841],
        [0.7665]])
tensor([[0.6837],
        [0.7464]])
tensor([[0.3580],
        [0.8613]])
tensor([[0.1302],
        [0.7593]])
tensor([[0.0810],
        [0.7390]])
tensor([[0.0149],
        [0.0127]])
tensor([[0.],
        [0.]])


In [ ]:
pfhedge.nn.functional.pl(stock.spot, m.delta())

### pfhedge.nn.functional.pl

In [ ]:
from torch import Tensor
from typing import Optional
from typing import List

def pl(
    spot: Tensor,
    unit: Tensor,
    cost: Optional[List[float]] = None,
    payoff: Optional[Tensor] = None,
    deduct_first_cost: bool = True,
    deduct_final_cost: bool = False,
) -> Tensor:
    r"""Returns the final profit and loss of hedging.

    For
    hedging instruments indexed by :math:`h = 1, \dots, H` and
    time steps :math:`i = 1, \dots, T`,
    the final profit and loss is given by

    .. math::
        \text{PL}(Z, \delta, S) =
            - Z
            + \sum_{h = 1}^{H} \sum_{t = 1}^{T} \left[
                    \delta^{(h)}_{t - 1} (S^{(h)}_{t} - S^{(h)}_{t - 1})
                    - c^{(h)} |\delta^{(h)}_{t} - \delta^{(h)}_{t - 1}| S^{(h)}_{t}
                \right] ,

    where
    :math:`Z` is the payoff of the derivative.
    For each hedging instrument,
    :math:`\{S^{(h)}_t ; t = 1, \dots, T\}` is the spot price,
    :math:`\{\delta^{(h)}_t ; t = 1, \dots, T\}` is the number of shares
    held at each time step.
    We define :math:`\delta^{(h)}_0 = 0` for notational convenience.

    A hedger sells the derivative to its customer and
    obliges to settle the payoff at maturity.
    The dealer hedges the risk of this liability
    by trading the underlying instrument of the derivative.
    The resulting profit and loss is obtained by adding up the payoff to the
    customer, capital gains from the underlying asset, and the transaction cost.

    References:
        - Buehler, H., Gonon, L., Teichmann, J. and Wood, B., 2019.
          Deep hedging. Quantitative Finance, 19(8), pp.1271-1291.
          [arXiv:`1802.03042 <https://arxiv.org/abs/1802.03042>`_ [q-fin]]

    Args:
        spot (torch.Tensor): The spot price of the underlying asset :math:`S`.
        unit (torch.Tensor): The signed number of shares of the underlying asset
            :math:`\delta`.
        cost (list[float], default=None): The proportional transaction cost rate of
            the underlying assets.
        payoff (torch.Tensor, optional): The payoff of the derivative :math:`Z`.
        deduct_first_cost (bool, default=True): Whether to deduct the transaction
            cost of the stock at the first time step.
            If ``False``, :math:`- c |\delta_0| S_1` is omitted the above
            equation of the terminal value.

    Shape:
        - spot: :math:`(N, H, T)` where
          :math:`N` is the number of paths,
          :math:`H` is the number of hedging instruments, and
          :math:`T` is the number of time steps.
        - unit: :math:`(N, H, T)`
        - payoff: :math:`(N)`
        - output: :math:`(N)`.

    Returns:
        torch.Tensor
    """
    # TODO(simaki): Support deduct_final_cost=True
    assert not deduct_final_cost, "not supported"

    if spot.size() != unit.size():
        raise RuntimeError(f"unmatched sizes: spot {spot.size()}, unit {unit.size()}")
    if payoff is not None:
        if payoff.dim() != 1 or spot.size(0) != payoff.size(0):
            raise RuntimeError(
                f"unmatched sizes: spot {spot.size()}, payoff {payoff.size()}"
            )

    output = unit[..., :-1].mul(spot.diff(dim=-1)).sum(dim=(-2, -1))

    if payoff is not None:
        output -= payoff

    if cost is not None:
        c = torch.tensor(cost).to(spot).unsqueeze(0).unsqueeze(-1)
        output -= (spot[..., 1:] * unit.diff(dim=-1).abs() * c).sum(dim=(-2, -1))
        if deduct_first_cost:
            output -= (spot[..., [0]] * unit[..., [0]].abs() * c).sum(dim=(-2, -1))

    return output



In [ ]:
stock.spot.size()

torch.Size([2, 21])

In [ ]:
spot = torch.stack([stock.spot], dim=1)
spot.size()

torch.Size([2, 1, 21])

In [ ]:
m.delta().size()

torch.Size([2, 21])

In [ ]:
m.delta().unsqueeze(1).size()

torch.Size([2, 1, 21])

In [ ]:
pl(spot, m.delta().unsqueeze(1))

tensor([-0.0210, -0.0353])

In [ ]:
outputs = []
for i in ds:
    outputs.append(m(i))

outputs = torch.cat(outputs, dim=-2)
outputs = outputs.transpose(-1,-2)
outputs

tensor([[[0.5113, 0.5437, 0.5260, 0.5570, 0.5506, 0.5906, 0.4279, 0.4419,
          0.5038, 0.5847, 0.6083, 0.4884, 0.4666, 0.7203, 0.7841, 0.6837,
          0.3580, 0.1302, 0.0810, 0.0149, 0.0000]],

        [[0.5113, 0.4451, 0.3618, 0.4419, 0.3753, 0.2024, 0.2027, 0.2976,
          0.3381, 0.2925, 0.2637, 0.5492, 0.6425, 0.7507, 0.7665, 0.7464,
          0.8613, 0.7593, 0.7390, 0.0127, 0.0000]]])

In [ ]:
output = unit[..., :-1].mul(spot.diff(dim=-1)).sum(dim=(-2, -1))

In [ ]:
spot.size()

torch.Size([2, 1, 21])

In [ ]:
outputs.size()

torch.Size([2, 1, 21])

In [ ]:
unit = outputs

In [ ]:
unit[..., :-1]

tensor([[[0.5113, 0.5437, 0.5260, 0.5570, 0.5506, 0.5906, 0.4279, 0.4419,
          0.5038, 0.5847, 0.6083, 0.4884, 0.4666, 0.7203, 0.7841, 0.6837,
          0.3580, 0.1302, 0.0810, 0.0149]],

        [[0.5113, 0.4451, 0.3618, 0.4419, 0.3753, 0.2024, 0.2027, 0.2976,
          0.3381, 0.2925, 0.2637, 0.5492, 0.6425, 0.7507, 0.7665, 0.7464,
          0.8613, 0.7593, 0.7390, 0.0127]]])

In [ ]:
unit[..., :-1].mul(spot.diff(dim=-1)).sum(dim=(-2, -1)).size()

torch.Size([2])