### entropic_risk_measure

In [ ]:
import torch
from torch import Tensor
import math

In [ ]:
def entropic_risk_measure(input: Tensor, a: float = 1.0) -> Tensor:
    """Returns the entropic risk measure.

    See :class:`pfhedge.nn.EntropicRiskMeasure` for details.
    """
    return (torch.logsumexp(-input * a, dim=0) - math.log(input.size(0))) / a

In [ ]:
x = -torch.arange(4.0)
x

tensor([-0., -1., -2., -3.])

In [ ]:
entropic_risk_measure(x)

tensor(2.0539)

In [ ]:
torch.logsumexp(-x, dim=0)

tensor(3.4402)

In [ ]:
-x

tensor([0., 1., 2., 3.])

In [ ]:
-x.exp()

tensor([-1.0000, -0.3679, -0.1353, -0.0498])

In [ ]:
-x.exp().sum()

tensor(-1.5530)

In [ ]:
-x.exp().sum().log()

tensor(-0.4402)

In [ ]:
import torch

# Define x as -torch.arange(4.0)
x = -torch.arange(4.0)

# logsumexp method (numerically stable)
result_stable = torch.logsumexp(-x, dim=0)

# Direct computation method (potentially unstable)
result_unstable = -x.exp().sum().log()

print("x:", x)
print("Result using torch.logsumexp:", result_stable)
print("Result using direct method:", result_unstable)

x: tensor([-0., -1., -2., -3.])
Result using torch.logsumexp: tensor(3.4402)
Result using direct method: tensor(-0.4402)


In [ ]:
import torch

# Example tensor with large and small values
x = torch.tensor([1000.0, 1000.1, 1000.2])

# logsumexp method (numerically stable)
result_stable = torch.logsumexp(-x, dim=0)

# Direct computation method (potentially unstable)
result_unstable = -x.exp().sum().log()

print("Result using torch.logsumexp:", result_stable)
print("Result using direct method:", result_unstable)

Result using torch.logsumexp: tensor(-998.9980)
Result using direct method: tensor(-inf)
